name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test with Rake
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install system dependencies
      run: sudo apt-get install build-essential libxml2-dev zlib1g-dev libcurl4-gnutls-dev
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
  build:
    name: Build Gem
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build gem
      run: |
         gem build *.gemspec
    - name: Upload gem
      uses: actions/upload-artifact@v2
      with:
        name: gem
        path: vagrant-aws-*.gem
